#pragma once

#include <stdint.h>

enum {
    CPUID_FEAT_ECX_SSE3         = 1U << 0,
    CPUID_FEAT_ECX_PCLMUL       = 1U << 1,
    CPUID_FEAT_ECX_DTES64       = 1U << 2,
    CPUID_FEAT_ECX_MONITOR      = 1U << 3,
    CPUID_FEAT_ECX_DS_CPL       = 1U << 4,
    CPUID_FEAT_ECX_VMX          = 1U << 5,
    CPUID_FEAT_ECX_SMX          = 1U << 6,
    CPUID_FEAT_ECX_EST          = 1U << 7,
    CPUID_FEAT_ECX_TM2          = 1U << 8,
    CPUID_FEAT_ECX_SSSE3        = 1U << 9,
    CPUID_FEAT_ECX_CID          = 1U << 10,
    CPUID_FEAT_ECX_SDBG         = 1U << 11,
    CPUID_FEAT_ECX_FMA          = 1U << 12,
    CPUID_FEAT_ECX_CX16         = 1U << 13,
    CPUID_FEAT_ECX_XTPR         = 1U << 14,
    CPUID_FEAT_ECX_PDCM         = 1U << 15,
    CPUID_FEAT_ECX_PCID         = 1U << 17,
    CPUID_FEAT_ECX_DCA          = 1U << 18,
    CPUID_FEAT_ECX_SSE4_1       = 1U << 19,
    CPUID_FEAT_ECX_SSE4_2       = 1U << 20,
    CPUID_FEAT_ECX_X2APIC       = 1U << 21,
    CPUID_FEAT_ECX_MOVBE        = 1U << 22,
    CPUID_FEAT_ECX_POPCNT       = 1U << 23,
    CPUID_FEAT_ECX_TSC          = 1U << 24,
    CPUID_FEAT_ECX_AES          = 1U << 25,
    CPUID_FEAT_ECX_XSAVE        = 1U << 26,
    CPUID_FEAT_ECX_OSXSAVE      = 1U << 27,
    CPUID_FEAT_ECX_AVX          = 1U << 28,
    CPUID_FEAT_ECX_F16C         = 1U << 29,
    CPUID_FEAT_ECX_RDRAND       = 1U << 30,
    CPUID_FEAT_ECX_HYPERVISOR   = 1U << 31,

    CPUID_FEAT_EDX_FPU          = 1U << 0,
    CPUID_FEAT_EDX_VME          = 1U << 1,
    CPUID_FEAT_EDX_DE           = 1U << 2,
    CPUID_FEAT_EDX_PSE          = 1U << 3,
    CPUID_FEAT_EDX_TSC          = 1U << 4,
    CPUID_FEAT_EDX_MSR          = 1U << 5,
    CPUID_FEAT_EDX_PAE          = 1U << 6,
    CPUID_FEAT_EDX_MCE          = 1U << 7,
    CPUID_FEAT_EDX_CX8          = 1U << 8,
    CPUID_FEAT_EDX_APIC         = 1U << 9,
    CPUID_FEAT_EDX_SEP          = 1U << 11,
    CPUID_FEAT_EDX_MTRR         = 1U << 12,
    CPUID_FEAT_EDX_PGE          = 1U << 13,
    CPUID_FEAT_EDX_MCA          = 1U << 14,
    CPUID_FEAT_EDX_CMOV         = 1U << 15,
    CPUID_FEAT_EDX_PAT          = 1U << 16,
    CPUID_FEAT_EDX_PSE36        = 1U << 17,
    CPUID_FEAT_EDX_PSN          = 1U << 18,
    CPUID_FEAT_EDX_CLFLUSH      = 1U << 19,
    CPUID_FEAT_EDX_DS           = 1U << 21,
    CPUID_FEAT_EDX_ACPI         = 1U << 22,
    CPUID_FEAT_EDX_MMX          = 1U << 23,
    CPUID_FEAT_EDX_FXSR         = 1U << 24,
    CPUID_FEAT_EDX_SSE          = 1U << 25,
    CPUID_FEAT_EDX_SSE2         = 1U << 26,
    CPUID_FEAT_EDX_SS           = 1U << 27,
    CPUID_FEAT_EDX_HTT          = 1U << 28,
    CPUID_FEAT_EDX_TM           = 1U << 29,
    CPUID_FEAT_EDX_IA64         = 1U << 30,
    CPUID_FEAT_EDX_PBE          = 1U << 31
};

int detect_cpu(void);

